{
 "title": "Cluster Resources",
 "description": "Display usage of resources by namespaces in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespaces",
    "query": {
     "query": "label_values(kube_resourcequota,namespace)"
    }
   },
   { "name": "added_cpu_request", "label": "+CPU request (cores)", "query": "0" },
   { "name": "added_cpu_limit", "label": "+CPU limit (cores)", "query": "0" },
   { "name": "added_memory_request", "label": "+Memory request (bytes)", "query": "0" },
   { "name": "added_memory_limit", "label": "+Memory limit (bytes)", "query": "0" },
   { "name": "node_down", "label": "Is Node Down", "query": "0,1" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# README\n\nThis dashboard display a cluster wide overview of the resource quota and usage so we can make a more informative decision.\n\nThis overview is on namespaces that we manage there quotas:\n\n${namespaces}"
   }
  },
  { "title": "CPU Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "(CPU) Namespaces Requests Quota  /  Cluster Resources",
   "type": "gauge",
   "description": "Percentage of sum of CPU Requests ResourceQuota on workers",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\", namespace=~\"$namespaces\"}) + ${added_cpu_request}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"cpu\", unit=\"core\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"cpu\",unit=\"core\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) Namespaces Limits Quota / Cluster Resources",
   "type": "gauge",
   "description": "Percentage of sum of CPU Limit ResourceQuota on workers",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\", namespace=~\"$namespaces\"}) + ${added_cpu_limit}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"cpu\", unit=\"core\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"cpu\",unit=\"core\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) Total Requests / Cluster Resources",
   "type": "gauge",
   "description": "Percentage of actual requests on workers",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(sum(kube_pod_container_resource_requests{node!~\".*(master).*\", resource=\"cpu\"}) + ${added_cpu_request}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"cpu\", unit=\"core\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"cpu\",unit=\"core\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(CPU) Allocated Requests by Namespace",
   "type": "piechart",
   "description": "100% is the sum of all allocated CPU Requests.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\", namespace=~\"$namespaces\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(CPU) Allocated Limits by Namespace",
   "type": "piechart",
   "description": "100% is the sum of all allocated CPU Limits.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=~\"$namespaces\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "CPU All Allocable Resources"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{ container!=\"POD\", node!~\"master.*\"}[1m]))",
     "legendFormat": "CPU Actual Usage"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\", type=\"hard\", namespace=~\"$namespaces\"})",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"hard\", namespace=~\"$namespaces\"})",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.cpu\", type=\"used\", namespace=~\"$namespaces\"})",
     "legendFormat": "CPU  Used Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.cpu\", type=\"used\",  namespace=~\"$namespaces\"})",
     "legendFormat": "CPU Used Requests"
    }
   ]
  },
  { "title": "Memory Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "(Memory) Namespaces Requests Quota  /  Cluster Resources",
   "type": "gauge",
   "description": "Percentage of sum of Memory Requests ResourceQuota on workers ",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "((sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\", namespace=~\"$namespaces\"})) + ${added_memory_request}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"memory\", unit=\"byte\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"memory\",unit=\"byte\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(Memory) Namespaces Limits Quota / Cluster Resources",
   "type": "gauge",
   "description": "Percentage of sum of Memory limit ResourceQuota on workers  ",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\", namespace=~\"$namespaces\"}) + ${added_memory_limit}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"memory\", unit=\"byte\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"memory\",unit=\"byte\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(Memory) Total Requests / Cluster Resources",
   "type": "gauge",
   "description": "Percentage of actual requests on workers ",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "(sum(kube_pod_container_resource_requests{ node!~\".*(master).*\", resource=\"memory\"}) + ${added_memory_request}) / (sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"memory\", unit=\"byte\"}) - sum(topk(1, kube_node_status_allocatable{node=~\".*(agent-).*\", resource=\"memory\",unit=\"byte\"})) * ${node_down}) * 100",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=\"$namespace\"}) / sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=\"$namespace\"}) * 100",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "(Memory) Allocated Requests by Namespace",
   "type": "piechart",
   "description": "100% is the sum of all allocated Memory Requests.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"requests.memory\",type=\"hard\", namespace=~\"$namespaces\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Memory) Allocated Limits by Namespace",
   "type": "piechart",
   "description": "100% is the sum of all allocated memory Limits.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (kube_resourcequota{resource=\"limits.memory\",type=\"hard\", namespace=~\"$namespaces\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node!~\".*(master).*\" ,resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "Memory All Allocable Resources"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{ container!=\"POD\", node!~\".*(master).*\", namespace=~\"$namespaces\"})",
     "legendFormat": "Memory Actual Usage"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\", type=\"hard\", namespace=~\"$namespaces\"})",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"hard\",  namespace=~\"$namespaces\"})",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"limits.memory\", type=\"used\",  namespace=~\"$namespaces\"})",
     "legendFormat": "Memory Used Limits"
    },
    {
     "expr": "sum(kube_resourcequota{resource=\"requests.memory\", type=\"used\",  namespace=~\"$namespaces\"})",
     "legendFormat": "Memory Used Requests"
    }
   ]
  }
 ]
}